apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: jenkins
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  DB_PASSWORD: YXV0aF9zdHJpbmc=  # Base64 encoded 'auth_string'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: jenkins
data:
  DB_HOST: "db"
  DB_NAME: "cerebro_db"
  DB_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: jenkins
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - name: cerebro
        image: joellots/cerebro:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  namespace: jenkins
spec:
  selector:
    app: cerebro
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cerebro-test
  namespace: jenkins
spec:
  template:
    spec:
      containers:
      - name: test-runner
        image: joellots/cerebro:latest
        command: ["sh", "-c", "pytest --cov --junitxml=/test-results.xml"]
        volumeMounts:
        - name: test-results
          mountPath: /test-results
      volumes:
      - name: test-results
        emptyDir: {}
      restartPolicy: Never

